import handle from "hono-react-router-adapter/cloudflare-workers";
// @ts-expect-error — generated by `pnpm build`, ships no type declarations
import * as build from "./build/server";
import app from "./server";
import { getLoadContext } from "./load-context";

export default handle(build, app, { getLoadContext });
