import { withSentry } from "@sentry/cloudflare";
import { sentryOptions } from "@starter/observability/sentry";
import handle from "hono-react-router-adapter/cloudflare-workers";
// @ts-expect-error — generated by `pnpm build`, ships no type declarations
import * as build from "./build/server";
import app from "./server";
import { getLoadContext } from "./load-context";
import type { ServerEnv } from "./server";

/**
 * `withSentry` wraps the whole Worker fetch handler, so it covers the Hono API
 * *and* React Router SSR, and auto-instruments the D1 binding.
 *
 * With no `SENTRY_DSN` set, `sentryOptions` returns undefined and this is a
 * pass-through — a fresh clone runs with no Sentry account.
 */
export default withSentry<ServerEnv["Bindings"]>(
  sentryOptions,
  handle(build, app, { getLoadContext }),
);
