// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/register": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/dashboard/settings": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/register" | "/dashboard" | "/dashboard/settings";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/register.tsx": {
    id: "routes/register";
    page: "/register";
  };
  "routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/dashboard" | "/dashboard/settings";
  };
  "routes/dashboard._index.tsx": {
    id: "routes/dashboard._index";
    page: "/dashboard";
  };
  "routes/dashboard.settings.tsx": {
    id: "routes/dashboard.settings";
    page: "/dashboard/settings";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/register": typeof import("./app/routes/register.tsx");
  "routes/dashboard": typeof import("./app/routes/dashboard.tsx");
  "routes/dashboard._index": typeof import("./app/routes/dashboard._index.tsx");
  "routes/dashboard.settings": typeof import("./app/routes/dashboard.settings.tsx");
};